production:
  solr:
    hostname: localhost
    port: 8983
    memory: 1G
    log_level: INFO
    path: '/solr/production'
    bind_address: 127.0.0.1
    pid_dir: 'tmp/pids'
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: '/solr/development'
    pid_dir: 'tmp/pids'

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: '/solr/test'
    bind_address: 127.0.0.1
    pid_dir: 'tmp/pids'

